// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdlmyI2ir_HcijsgKRCiSTzAq3HVOSG7E',
    appId: '1:342115266309:android:6c42ffab4469768be6116c',
    messagingSenderId: '342115266309',
    projectId: 'habit-tracker-225ce',
    storageBucket: 'habit-tracker-225ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdlmyI2ir_HcijsgKRCiSTzAq3HVOSG7E',
    appId: '1:342115266309:ios:6c42ffab4469768be6116c',
    messagingSenderId: '342115266309',
    projectId: 'habit-tracker-225ce',
    storageBucket: 'habit-tracker-225ce.firebasestorage.app',
    iosBundleId: 'com.example.habitsTrackerApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdlmyI2ir_HcijsgKRCiSTzAq3HVOSG7E',
    appId: '1:342115266309:web:6c42ffab4469768be6116c',
    messagingSenderId: '342115266309',
    projectId: 'habit-tracker-225ce',
    storageBucket: 'habit-tracker-225ce.firebasestorage.app',
    authDomain: 'habit-tracker-225ce.firebaseapp.com',
  );
}
