// import 'package:device_preview_plus/device_preview_plus.dart';
// import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:shared_preferences/shared_preferences.dart'; //  New import

import 'firebase_options.dart'; //  generated by FlutterFire CLI
import 'splash_screen/splash_screen.dart';
import 'onbourding_screen/onbourding_screen.dart'; //  Uncommented

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // 1. Load SharedPreferences
  final prefs = await SharedPreferences.getInstance();
  // 2. Check if onboarding has been seen
  final bool hasSeenOnboarding = prefs.getBool('hasSeenOnboarding') ?? false;

  runApp(
    // DevicePreview(
    //   enabled: !kReleaseMode, // only enable on debug builds
    //   builder: (context) =>
    MyApp(hasSeenOnboarding: hasSeenOnboarding), //  Pass the flag to MyApp
    // ),
  );
}

class MyApp extends StatelessWidget {
  // 👈 New constructor to receive the flag
  final bool hasSeenOnboarding;
  const MyApp({super.key, required this.hasSeenOnboarding});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,

      // ///  Required for DevicePreview
      // useInheritedMediaQuery: true,
      // locale: DevicePreview.locale(context),
      // builder: DevicePreview.appBuilder,

      ///  Your first screen
      //  Conditional rendering based on the flag
      home: hasSeenOnboarding ? const SplashScreen() : const OnboardingScreen(),
    );
  }
}